# To use with https://esphomelib.com/esphomeyaml/
#
esphomeyaml:
  name: simple_ambient_sensor
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'wireless'
  password: 'Netzgesichert123'

mqtt:
  broker: '192.168.0.30'
  username: ''
  password: ''
  discovery_prefix: home

logger:
ota:

web_server:
  port: 80

i2c:
  sda: 21
  scl: 22
  scan: False

binary_sensor:
  - platform: status
    name: "Ambient Sensor Status"

switch:
  - platform: restart
    name: "Ambient Sensor Restart"

sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 15s

